### PR TITLE
Perf

### PR DESCRIPTION
**Pull request by meztez**
Performance refactor, adding a `nthread` parameter to downscale.

```r
library(terra)
library(climRpnw)
scenario <- "ssp245"
proj.year <- "2041"
# Provide or create a points dataframe (lon, lat, elev)
studyarea <- "Quesnel"
grid <- read.csv("tests/Quesnel.csv", stringsAsFactors=F)
xyz <- grid[,c(4,3,5)]

system.time({
normal <- normal_input()
gcms <- list_gcm()
gcm = gcms[5]
vars.all <- list_variables()
gcmquery <- gcm_input(
  gcm = gcm,
  ssp = c("ssp245"),
  period = "2041_2060",
  max_run = 0
)
climr2 <- downscale(
  xyz = xyz,
  normal = normal,
  gcm = gcmquery,
  var = vars.all,
  nthread = 4
)
})
```
Should run 10x faster than previous iteration.

Benefits increase as you have more points or use smaller area with more points.

### CODE REVIEW

**Comment by cmahony** [comment]
@meztez thanks for this work! I'm finding the downscale function is unchanged, still about 25x ClimateBC speed on the Quesnel test data with nthread=1. when i increase nthread it slows it down a lot (5x slower for nthread=4). wondering if I'm not applying this properly. 


```
> system.time({
+   climr2 <- downscale(
+     xyz = xyz,
+     normal = normal,
+     gcm = gcmquery,
+     var = vars.all,
+     nthread = 4
+   )
+ })
   user  system elapsed 
   1.52    0.92   21.19 
> system.time({
+   climr2 <- downscale(
+     xyz = xyz,
+     normal = normal,
+     gcm = gcmquery,
+     var = vars.all,
+     nthread = 1
+   )
+ })
   user  system elapsed 
   5.30    0.59    4.30 
> system.time({
+   climr2 <- downscale(
+     xyz = xyz,
+     normal = normal,
+     gcm = gcmquery,
+     var = vars.all,
+     nthread = 2
+   )
+ })
   user  system elapsed 
   0.92    0.65   14.56 
```

**Comment by meztez** [comment]
Multithreading on R windows does not work the same as Linux. Using PsockCluster vs ForkCluster. 

Multiple things can affect performance, disk performance for cached data, memory speed, memory size.

What I am seeing on my end is a 10x performance boost from loading less raster values from disk to memory and extracting only once instead of three times.

There are probably further optimizations depending on how the package is used.

I'll switch OS to profile the code to see where it spends most of its time, see if I can squeeze it further.

**Comment by meztez** [comment]
> @meztez thanks for this work! I'm finding the downscale function is unchanged, still about 25x ClimateBC speed on the Quesnel test data with nthread=1. when i increase nthread it slows it down a lot (5x slower for nthread=4). wondering if I'm not applying this properly. 
> 
> 
> ```
> > system.time({
> +   climr2 <- downscale(
> +     xyz = xyz,
> +     normal = normal,
> +     gcm = gcmquery,
> +     var = vars.all,
> +     nthread = 4
> +   )
> + })
>    user  system elapsed 
>    1.52    0.92   21.19 
> > system.time({
> +   climr2 <- downscale(
> +     xyz = xyz,
> +     normal = normal,
> +     gcm = gcmquery,
> +     var = vars.all,
> +     nthread = 1
> +   )
> + })
>    user  system elapsed 
>    5.30    0.59    4.30 
> > system.time({
> +   climr2 <- downscale(
> +     xyz = xyz,
> +     normal = normal,
> +     gcm = gcmquery,
> +     var = vars.all,
> +     nthread = 2
> +   )
> + })
>    user  system elapsed 
>    0.92    0.65   14.56 
> ```

I just saw you did not include normal_input and gcm_input in your timing. How long was it to load normal on your end before? It's almost instant now.

**Comment by cmahony** [comment]
how long does your example code take to run on your Linux machine?

**Comment by cmahony** [comment]
Yes, the normal_input and gcm_input are way faster/instant. nice!!

**Comment by meztez** [comment]
```r
library(terra)
library(climRpnw)
scenario <- "ssp245"
proj.year <- "2041"
# Provide or create a points dataframe (lon, lat, elev)
studyarea <- "Quesnel"
grid <- read.csv("tests/Quesnel.csv", stringsAsFactors=F)
xyz <- grid[,c(4,3,5)]

normal <- normal_input()
gcm <- gcm_input(list_gcm()[5], "ssp245", "2041_2060")

# ~110000 points
microbenchmark::microbenchmark(
  "1thread" = {downscale(xyz, normal, gcm, nthread = 1)},
  "2threads" = {downscale(xyz, normal, gcm, nthread = 2)},
  "4threads" = {downscale(xyz, normal, gcm, nthread = 4)},
  "8threads" = {downscale(xyz, normal, gcm, nthread = 8)},
  times = 2
)

xyz <- rbind(xyz, xyz, xyz, xyz, xyz, xyz, xyz, xyz, xyz, xyz)

# ~1100000 points
microbenchmark::microbenchmark(
  "1thread" = {downscale(xyz, normal, gcm, nthread = 1)},
  "2threads" = {downscale(xyz, normal, gcm, nthread = 2)},
  "4threads" = {downscale(xyz, normal, gcm, nthread = 4)},
  "8threads" = {downscale(xyz, normal, gcm, nthread = 8)},
  times = 2
)
```

```
> # ~110000 points
> microbenchmark::microbenchmark(
+   "1thread" = {downscale(xyz, normal, gcm, nthread = 1)},
+   "2threads" = {downscale(xyz, normal, gcm, nthread = 2)},
+   "4threads" = {downscale(xyz, normal, gcm, nthread = 4)},
+   "8threads" = {downscale(xyz, normal, gcm, nthread = 8)},
+   times = 2
+ )
Unit: seconds
     expr      min       lq     mean   median       uq      max neval
  1thread 1.875563 1.875563 1.891764 1.891764 1.907964 1.907964     2
 2threads 1.827200 1.827200 1.939578 1.939578 2.051956 2.051956     2
 4threads 1.858223 1.858223 1.910998 1.910998 1.963774 1.963774     2
 8threads 2.544760 2.544760 2.653608 2.653608 2.762456 2.762456     2
```

```
> # ~1100000 points
> microbenchmark::microbenchmark(
+   "1thread" = {downscale(xyz, normal, gcm, nthread = 1)},
+   "2threads" = {downscale(xyz, normal, gcm, nthread = 2)},
+   "4threads" = {downscale(xyz, normal, gcm, nthread = 4)},
+   "8threads" = {downscale(xyz, normal, gcm, nthread = 8)},
+   times = 2
+ )
Unit: seconds
     expr       min        lq     mean   median       uq      max neval
  1thread 19.191367 19.191367 19.74159 19.74159 20.29180 20.29180     2
 2threads 13.116259 13.116259 14.70476 14.70476 16.29326 16.29326     2
 4threads  9.771215  9.771215 10.09687 10.09687 10.42253 10.42253     2
 8threads  9.903979  9.903979 10.03219 10.03219 10.16040 10.16040     2
```

The tradeoff where it makes sense to go multithread seems to be around 250k-300k points.

There is also an overhead to computing some climate variables (Eref), so I would probably compute only what is needed.

**Comment by cmahony** [comment]
Cool. this all makes sense. nice machine you've got there. thanks again for the optimization!

**Comment by cmahony** [comment]
i got a 3x speed boost with nthread on 1.6M points. nice!

**Comment by meztez** [comment]
Most time is spent reformating output from dcasting. Let me try an ugly hack to cut that time down.

**Comment by cmahony** [comment]
performance tests: 

image

**Comment by meztez** [comment]
Nice, you are probably running single channel memory on a 4 cores, 8 thread CPUs. This will heavily be architecture independent. On a quad channel, dual socket AMD epic server, this thing will purr.

**Comment by meztez** [comment]
Switched from a data.table melt/dcast workflow, to a groupset stacking approach.

New timings:
```
> # ~110000 points
> microbenchmark::microbenchmark(
+   "1thread" = {downscale(xyz, normal, gcm, nthread = 1)},
+   "2threads" = {downscale(xyz, normal, gcm, nthread = 2)},
+   "4threads" = {downscale(xyz, normal, gcm, nthread = 4)},
+   "8threads" = {downscale(xyz, normal, gcm, nthread = 8)},
+   times = 2
+ )
 Unit: seconds
     expr      min       lq     mean   median       uq      max neval
  1thread 1.121697 1.121697 1.303822 1.303822 1.485947 1.485947     2
 2threads 1.210672 1.210672 1.218438 1.218438 1.226205 1.226205     2
 4threads 1.277337 1.277337 1.327952 1.327952 1.378567 1.378567     2
 8threads 2.020878 2.020878 2.026090 2.026090 2.031301 2.031301     2
```

```
> # ~1100000 points
> microbenchmark::microbenchmark(
+   "1thread" = {downscale(xyz, normal, gcm, nthread = 1)},
+   "2threads" = {downscale(xyz, normal, gcm, nthread = 2)},
+   "4threads" = {downscale(xyz, normal, gcm, nthread = 4)},
+   "8threads" = {downscale(xyz, normal, gcm, nthread = 8)},
+   times = 2
+ )
Unit: seconds
     expr       min        lq      mean    median        uq       max neval
  1thread 10.058943 10.058943 10.061615 10.061615 10.064286 10.064286     2
 2threads  5.857674  5.857674  6.795661  6.795661  7.733648  7.733648     2
 4threads  4.963946  4.963946  5.141084  5.141084  5.318222  5.318222     2
 8threads  5.155288  5.155288  5.253206  5.253206  5.351125  5.351125     2
```

So about 66% faster to 97% faster for larger number of points.

New flame graph
Screenshot from 2022-04-09 19-15-30

Most time is now spent in .External (terra::extract). So any improvement in the underlying library will have a huge impact on this package going forward.

**Comment by cmahony** [comment]
Hi @meztez, the new version isn't faster on my computer, but is more unstable. My 1.5M-point raster runs 50secs on 4 threads, but anywhere from 110s to 800s on one thread, and generally >400s. it used to be 49s on 4 threads and consistently ~130s on one thread.  in the trials below, you can see that the 1.5M-point dataset gets different results in the two bottom panels with one thread. 

image

**Comment by cmahony** [comment]
I uploaded the [dem2_WNA.tif](https://github.com/bcgov/climR-pnw/blob/main/tests/dem2_WNA.tif) 1.5M point raster to the tests folder

**Comment by meztez** [comment]
Probably due to memory restriction on your system. I'll switch this to another branch while I work out memory usage.

**Comment by meztez** [comment]
I've tested both version, the one using the ugly hack uses half the memory and is faster. Wondering about what machine your are testing on and if performance is hindered by the available memory.

dcast / melt workflow
```
> perf <- bench::mark("perf" = downscale(xyz, normal, gcm, nthread = 1))
> perf
# A tibble: 1 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
1 perf          16.8s    16.8s    0.0595    14.7GB    0.298     1     5      16.8s
# … with 4 more variables: result <list>, memory <list>, time <list>, gc <list>
```

alternative ugly hack
```
> perf2 <- bench::mark("perf2" = downscale(xyz, normal, gcm, nthread = 1))
> perf2
# A tibble: 1 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
1 perf2         9.25s    9.25s     0.108    7.65GB    0.757     1     7
# … with 5 more variables: total_time <bch:tm>, result <list>,
#   memory <list>, time <list>, gc <list>
```

**Comment by cmahony** [comment]
ThinkPad with 32GB memory, 6 intel cores @2.7GHz.

**Comment by meztez** [comment]
Does not seem likely with 32Gb...

**Pull request merged**
